### ISSUE TITLE
ResourceNotFound exception when entering text

### ISSUE THREAD

**Issue by vvallabb** [splitwise/TokenAutoComplete#104]
I am getting this dump:
Steps to reproduce:
1. Implement the example
2. type "am" in ContactsCompletionView [which means the string is present]

 android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010022 a=2}
            at android.content.res.Resources.loadDrawable(Resources.java:2071)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.widget.AbsListView.<init>(AbsListView.java:785)
            at android.widget.ListView.<init>(ListView.java:146)
            at android.widget.ListPopupWindow$DropDownListView.<init>(ListPopupWindow.java:1446)
            at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1038)
            at android.widget.ListPopupWindow.show(ListPopupWindow.java:554)
            at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1096)
            at android.widget.AutoCompleteTextView.updateDropDownForFilter(AutoCompleteTextView.java:971)
            at android.widget.AutoCompleteTextView.onFilterComplete(AutoCompleteTextView.java:953)
            at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mgod** [comment]
What OS/device are you targeting?

**Comment by vvallabb** [comment]
My build.gradle:

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        ...
        minSdkVersion 15
        targetSdkVersion 21
     }
...
}

**Comment by vvallabb** [comment]
I found the issue. It was in my styles.xml. You can close this issue.

I had to search for **0x7f010022** from dump and found the issue pointing to this from R.java. 
I had to **remove/comment** the following lines to get the dropdown styling to work.

styles.xml
----------------
```xml
...
<item name="android:popupMenuStyle">@style/Widget.Vas.PopupMenu</item>
<item name="android:listPopupWindowStyle">@style/Widget.Vas.PopupMenu</item>
<item name="android:dropDownListViewStyle">@style/Widget.Vas.ListView.DropDown</item>

 <style name="Widget.Vas.PopupMenu" parent="Widget.AppCompat.Light.PopupMenu">
        <item name="android:dropDownSelector">?popupItemBackground</item>
</style>

     <style name="Widget.Vas.ListView.DropDown" parent="Widget.AppCompat.Light.ListView.DropDown">
        <item name="android:listSelector">?popupItemBackground</item>
        <item name="android:divider">@null</item>
        <item name="android:dividerHeight">0dp</item>
    </style>
