### ISSUE TITLE
PopupWindow$PopupViewContainer{3b0009a7 V.E..... ......I. 0,0-0,0} not attached to window manager

### ISSUE THREAD

**Issue by TheGreat0004** [splitwise/TokenAutoComplete#196]
Fatal Exception: java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupViewContainer{3b0009a7 V.E..... ......I. 0,0-0,0} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.widget.PopupWindow.dismiss(PopupWindow.java:1405)
       at android.widget.ListPopupWindow.dismiss(ListPopupWindow.java:656)
       at android.widget.AutoCompleteTextView.dismissDropDown(AutoCompleteTextView.java:1042)
       at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1019)
       at cl.dummy.ui.custom_view.tokenautocomplete.TokenCompleteTextView.onFocusChanged(TokenCompleteTextView.java:714)
       at android.view.View.clearFocusInternal(View.java:5089)
       at android.view.View.unFocus(View.java:5122)
       at android.view.ViewGroup.requestChildFocus(ViewGroup.java:658)
       at android.view.ViewGroup.requestChildFocus(ViewGroup.java:664)
       at android.view.View.handleFocusGainInternal(View.java:4955)
       at android.view.View.requestFocusNoSearch(View.java:7678)
       at android.view.View.requestFocus(View.java:7657)
       at android.view.View.requestFocus(View.java:7624)
       at android.view.View.requestFocus(View.java:7603)
       at cl.dummy.ui.fragments.PostNeeds.onScrollChanged(PostNeeds.java:283)
       at cl.dummy.ui.custom_view.ExampleScrollView.onScrollChanged(ExampleScrollView.java:32)
       at android.view.View.scrollTo(View.java:11505)
       at android.widget.ScrollView.scrollTo(ScrollView.java:1626)
       at android.view.View.scrollBy(View.java:11520)
       at android.widget.ScrollView.scrollToChildRect(ScrollView.java:1349)
       at android.widget.ScrollView.requestChildRectangleOnScreen(ScrollView.java:1477)
       at android.view.View.requestRectangleOnScreen(View.java:5029)
       at android.widget.PopupWindow.findDropDownPosition(PopupWindow.java:1263)
       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1001)
       at android.widget.ListPopupWindow.show(ListPopupWindow.java:639)
       at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1105)
       at android.widget.AutoCompleteTextView.updateDropDownForFilter(AutoCompleteTextView.java:974)
       at android.widget.AutoCompleteTextView.onFilterComplete(AutoCompleteTextView.java:956)
       at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by mgod** [comment]
I'm pretty sure this isn't an issue with TokenAutoComplete, but not having it attached to a window when you're requesting focus on it. If you can provide steps to reproduce this in the example project or some similar demo, I'd be happy to look into it more.
