### ISSUE TITLE
TokenCompleteTextView that accept free text next to chips

### ISSUE THREAD

**Issue by mslobodan** [splitwise/TokenAutoComplete#268]
I am trying to use this lib to accept text next to chips, but without luck. 
I got this exception:
`E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.xxx.yyy, PID: 7859
 java.lang.IndexOutOfBoundsException: charAt: 12 >= length 12
     at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:116)
     at com.tokenautocomplete.TokenCompleteTextView$TokenTextWatcher.afterTextChanged(TokenCompleteTextView.java:1325)
     at android.widget.TextView.sendAfterTextChanged(TextView.java:9078)
     at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11739)
     at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:976)
     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:520)
     at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:216)
     at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:33)
     at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:246)
     at android.view.inputmethod.InputConnectionWrapper.deleteSurroundingText(InputConnectionWrapper.java:66)
     at com.tokenautocomplete.TokenCompleteTextView$TokenInputConnection.deleteSurroundingText(TokenCompleteTextView.java:1561)
     at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:389)
     at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:145)
     at android.app.ActivityThread.main(ActivityThread.java:6938)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

Can someone check full question I posted on stackoverflow:
[TokenCompleteTextView that accept free text next to chips](http://stackoverflow.com/questions/41357684/tokencompletetextview-that-accept-free-text-next-to-chips)

**Comment by mslobodan** [comment]
It was problem with my tokenizer implementation.
