### ISSUE TITLE
IndexOutofBoundException at  at com.tokenautocomplete.TokenCompleteTextView.performCollapse(TokenCompleteTextView.java:749)                                                                          at com.tokenautocomplete.TokenCompleteTextView.onFocusChanged(TokenCompleteTextView.java:830)

### ISSUE THREAD

**Issue by riyase** [splitwise/TokenAutoComplete#328]
java.lang.RuntimeException: Unable to destroy activity java.lang.IndexOutOfBoundsException: replace (1 ... 1) ends beyond length 0
                                                                         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4208)
                                                                         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
                                                                         at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                      Caused by: java.lang.IndexOutOfBoundsException: replace (1 ... 1) ends beyond length 0
                                                                         at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1271)
                                                                         at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
                                                                         at android.text.SpannableStringBuilder.insert(SpannableStringBuilder.java:225)
                                                                         at android.text.SpannableStringBuilder.insert(SpannableStringBuilder.java:224)
                                                                         at com.tokenautocomplete.TokenCompleteTextView.performCollapse(TokenCompleteTextView.java:749)
                                                                         at com.tokenautocomplete.TokenCompleteTextView.onFocusChanged(TokenCompleteTextView.java:830)
                                                                         at android.view.View.clearFocusInternal(View.java:6064)
                                                                         at android.view.View.unFocus(View.java:6097)
                                                                         at android.view.ViewGroup.unFocus(ViewGroup.java:997)
                                                                         at android.view.ViewGroup.unFocus(ViewGroup.java:997)
                                                                         at android.view.ViewGroup.unFocus(ViewGroup.java:997)
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4743)
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4730)
                                                                         at android.view.ViewGroup.removeView(ViewGroup.java:4661)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1452)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3028)
                                                                         at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
                                                                         at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
                                                                         at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
                                                                         at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1175)
                                                                         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4195)
                                                                         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226) 
                                                                         at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by riyase** [comment]
by mistake i was calling setText("") just after calling Activity.finish()

**Comment by Kapil-Bhattarai** [comment]
I am also having the same problem... did you just solved this issues by removing  setText("") ?

**Comment by mgod** [comment]
Generally you should not use ```setText``` at all in this class. I'd make it private if I could. ```clear``` is probably what you're looking for.

**Comment by mgod** [comment]
it's possible `clearCompletionText` might also be what you're looking for, as `performCompletion` will actually produce a token in some cases depending on your configuration.

**Comment by andreaciri** [comment]
Unfortunately `clearCompletionText`doesn't seem to be an available method. I'm using version `2.0.8`.
