### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by Nebeloxas** [splitwise/TokenAutoComplete#334]
Hey, I tried tu run this for 4 hours and still i keep getting same error: 

> 12-13 03:47:54.638 6217-6217/com.giraffity.giraffity E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.giraffity.giraffity, PID: 6217
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.giraffity.giraffity/com.giraffity.giraffity.EditActivity}: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class com.tokenautocomplete.TokenCompleteTextView
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                        Caused by: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class com.tokenautocomplete.TokenCompleteTextView
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                           at com.giraffity.giraffity.EditActivity.onCreate(EditActivity.java:53)
                                                                           at android.app.Activity.performCreate(Activity.java:6876)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: android.view.InflateException: Binary XML file line #94: Error inflating class com.tokenautocomplete.TokenCompleteTextView
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                           at com.giraffity.giraffity.EditActivity.onCreate(EditActivity.java:53) 
                                                                           at android.app.Activity.performCreate(Activity.java:6876) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: java.lang.InstantiationException: Can't instantiate abstract class com.tokenautocomplete.TokenCompleteTextView
                                                                           at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                           at com.giraffity.giraffity.EditActivity.onCreate(EditActivity.java:53) 
                                                                           at android.app.Activity.performCreate(Activity.java:6876) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

on this line it crashes "setContentView(R.layout.activity_edit);"
because of this in xml file:

>         <com.tokenautocomplete.TokenCompleteTextView
>             android:id="@+id/tagsEdit"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content" />

I tried writing as in example with 

> com.tokenautocomplete.ContactsCompletionView

and with 
> com.giraffity.giraffity.ContactsCompletionView
still nothing worked.

**Comment by mgod** [comment]
Can you show me the error when you use your own subclass of ```TokenCompleteTextView```? It's an abstract class, so you must subclass it and use that subclass in your XML layout.
