### ISSUE TITLE
IndexOutOfBoundsException Perform Cut perform on typed text.

### ISSUE THREAD

**Issue by hmittal1** [splitwise/TokenAutoComplete#335]
This is reproducible on android >= 8.0.
Steps:
type 2-3 chars , select all chars and then perform "cut" perform. app crashed.

Fatal Exception: java.lang.IndexOutOfBoundsException: charAt: 9 >= length 9
       at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:123)
       at android.text.CharSequenceCharacterIterator.current(CharSequenceCharacterIterator.java:58)
       at android.text.CharSequenceCharacterIterator.setIndex(CharSequenceCharacterIterator.java:83)
       at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:929)
       at android.text.method.WordIterator.isBoundary(WordIterator.java:95)
       at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Editor.java:4983)
       at android.widget.Editor$HandleView.invalidate(Editor.java:4285)
       at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Editor.java:5624)
       at android.widget.Editor.invalidateHandlesAndActionMode(Editor.java:1855)
       at android.widget.TextView.setShadowLayer(TextView.java:4121)
       at com.tokenautocomplete.TokenCompleteTextView.api16Invalidate(TokenCompleteTextView.java:511)
       at com.tokenautocomplete.TokenCompleteTextView.invalidate(TokenCompleteTextView.java:520)
       at android.widget.TextView.updateAfterEdit(TextView.java:9407)

Please fix this issue.

**Comment by mgod** [comment]
Cut, copy and paste aren't really supported by this view and I thought I'd disabled all the interactions that would expose this functionality. I'll try to take a look at this when I have the time, but my solution is likely going to be finding more ways to disable things than make them work correctly.
