### ISSUE TITLE
StackOverflowError on resume / exit

### ISSUE THREAD

**Issue by Saketme** [splitwise/TokenAutoComplete#72]
TokenAutoComplete has started throwing an exception lately whose log you can find at below. It generally occurs after resuming the app after a while. Either the app crashes or it takes a significant duration of time to resume.

    08-06 21:13:24.295  28751-28751/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.splurge.smsx, PID: 28751
    java.lang.StackOverflowError: stack size 7MB
            at android.widget.TextView.makeNewLayout(TextView.java:6080)
            at android.widget.TextView.checkForRelayout(TextView.java:6619)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8720)
            at android.view.View.resolvePadding(View.java:12865)
            at android.view.View.getPaddingLeft(View.java:16069)
            at com.splurge.smsx.customviews.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:262)
            at com.splurge.smsx.customviews.TokenCompleteTextView.access$1000(TokenCompleteTextView.java:55)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:797)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:816)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:207)
            at android.text.StaticLayout.generate(StaticLayout.java:280)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
            at android.widget.TextView.makeSingleLayout(TextView.java:6182)
            at android.widget.TextView.makeNewLayout(TextView.java:6080)
            at android.widget.TextView.checkForRelayout(TextView.java:6619)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8720)
            at android.view.View.resolvePadding(View.java:12865)
            at android.view.View.getPaddingLeft(View.java:16069)
            at com.splurge.smsx.customviews.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:262)
            at com.splurge.smsx.customviews.TokenCompleteTextView.access$1000(TokenCompleteTextView.java:55)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:797)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:816)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:207)
            at android.text.StaticLayout.generate(StaticLayout.java:280)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
            at android.widget.TextView.makeSingleLayout(TextView.java:6182)
            at android.widget.TextView.makeNewLayout(TextView.java:6080)
            at android.widget.TextView.checkForRelayout(TextView.java:6619)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8720)
            at android.view.View.resolvePadding(View.java:12865)
            at android.view.View.getPaddingLeft(View.java:16069)
            at com.splurge.smsx.customviews.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:262)
            at com.splurge.smsx.customviews.TokenCompleteTextView.access$1000(TokenCompleteTextView.java:55)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:797)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:816)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:207)
            at android.text.StaticLayout.generate(StaticLayout.java:280)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
            at android.widget.TextView.makeSingleLayout(TextView.java:6182)
            at android.widget.TextView.makeNewLayout(TextView.java:6080)
            at android.widget.TextView.checkForRelayout(TextView.java:6619)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8720)
            at android.view.View.resolvePadding(View.java:12865)
            at android.view.View.getPaddingLeft(View.java:16069)
            at com.splurge.smsx.customviews.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:262)
            at com.splurge.smsx.customviews.TokenCompleteTextView.access$1000(TokenCompleteTextView.java:55)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:797)
            at com.splurge.smsx.customviews.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:816)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:207)
            at android.text.StaticLayout.generate(StaticLayout.java:280)
            at android.text.DynamicLay

Any idea how to fix this?

**Comment by Saketme** [comment]
Wow, I'm sorry for replying so late. I must have overlooked my notifications :/ This bug appears in my code. I'm running on Android 5.0 Lollipop.

**Comment by Saketme** [comment]
@mgod I think I figured out how to reproduce this bug. Animating the window's background color while tokens are present produces an infinite loop, resulting in this StackOverflow error. Here's a sample code:

https://gist.github.com/0682ed3805cfc442ca25

**Comment by hellobenny** [comment]
I get the same error too:

java.lang.StackOverflowError: stack size 8MB
            at android.widget.TextView.makeSingleLayout(TextView.java:6405)
            at android.widget.TextView.makeNewLayout(TextView.java:6303)
            at android.widget.TextView.checkForRelayout(TextView.java:6842)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8945)
            at android.view.View.resolvePadding(View.java:13356)
            at android.view.View.getPaddingLeft(View.java:16605)
            at com.tokenautocomplete.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:362)
            at com.tokenautocomplete.TokenCompleteTextView.access$1100(TokenCompleteTextView.java:57)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:1022)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:1041)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:206)
            at android.text.StaticLayout.generate(StaticLayout.java:285)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
            at android.widget.TextView.makeSingleLayout(TextView.java:6405)
            at android.widget.TextView.makeNewLayout(TextView.java:6303)
            at android.widget.TextView.checkForRelayout(TextView.java:6842)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8945)
            at android.view.View.resolvePadding(View.java:13356)
            at android.view.View.getPaddingLeft(View.java:16605)
            at com.tokenautocomplete.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:362)
            at com.tokenautocomplete.TokenCompleteTextView.access$1100(TokenCompleteTextView.java:57)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:1022)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:1041)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:206)
            at android.text.StaticLayout.generate(StaticLayout.java:285)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
            at android.widget.TextView.makeSingleLayout(TextView.java:6405)
            at android.widget.TextView.makeNewLayout(TextView.java:6303)
            at android.widget.TextView.checkForRelayout(TextView.java:6842)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8945)
            at android.view.View.resolvePadding(View.java:13356)
            at android.view.View.getPaddingLeft(View.java:16605)
            at com.tokenautocomplete.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:362)
            at com.tokenautocomplete.TokenCompleteTextView.access$1100(TokenCompleteTextView.java:57)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:1022)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:1041)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:206)
            at android.text.StaticLayout.generate(StaticLayout.java:285)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
            at android.widget.TextView.makeSingleLayout(TextView.java:6405)
            at android.widget.TextView.makeNewLayout(TextView.java:6303)
            at android.widget.TextView.checkForRelayout(TextView.java:6842)
            at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8945)
            at android.view.View.resolvePadding(View.java:13356)
            at android.view.View.getPaddingLeft(View.java:16605)
            at com.tokenautocomplete.TokenCompleteTextView.maxTextWidth(TokenCompleteTextView.java:362)
            at com.tokenautocomplete.TokenCompleteTextView.access$1100(TokenCompleteTextView.java:57)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.prepView(TokenCompleteTextView.java:1022)
            at com.tokenautocomplete.TokenCompleteTextView$ViewSpan.getSize(TokenCompleteTextView.java:1041)
            at android.text.MeasuredText.addStyleRun(MeasuredText.java:206)
            at android.text.StaticLayout.generate(StaticLayout.java:285)
            at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
            at android.text.DynamicLayout.<init>(DynamicLayout.j

**Comment by mgod** [comment]
@hellobenny I still haven't had time to reproduce this using the earlier gist. Are you also seeing problems with this when you're animating the view or do you have some other case that breaks the view? I spent a little time getting the gist working in the example project, but ran into a couple of issues and haven't had time to work it out. If you can provide reproduction steps for the example project, it'll be much easier for me to fix this.

**Comment by hellobenny** [comment]
@mgod I believe I was just setting the field and clearing it repeatedly in the same activity.

**Comment by ShilkumarJ** [comment]
java.lang.StackOverflowError
                                                                                                      at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:63)
                                                                                                      at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:39)
                                                                                                      at android.view.GLES20RecordingCanvas$1.newInstance(GLES20RecordingCanvas.java:47)
                                                                                                      at android.view.GLES20RecordingCanvas$1.newInstance(GLES20RecordingCanvas.java:45)
                                                                                                      at android.util.FinitePool.acquire(FinitePool.java:69)
                                                                                                      at android.util.SynchronizedPool.acquire(SynchronizedPool.java:39)
                                                                                                      at android.view.GLES20RecordingCanvas.obtain(GLES20RecordingCanvas.java:67)
                                                                                                      at android.view.GLES20DisplayList.start(GLES20DisplayList.java:52)
                                                                                                      at android.view.View.getDisplayList(View.java:10425)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                                      at android.view.View.getDisplayList(View.java:10444)
                                                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                                  	at android.view.V

**Comment by Saketme** [comment]
@ShilkumarJ Are you using the latest version of this library? If I recall correctly, updating to the latest version had fixed the issue for me.
